{{- if .Values.metrics.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kafka.fullname" . }}-exporter
  labels:
    app.kubernetes.io/name: {{ template "kafka.name" . }}
    helm.sh/chart: {{ template "kafka.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "kafka.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "kafka.name" . }}
        helm.sh/chart: {{ template "kafka.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: metrics
    spec:
{{- include "kafka.imagePullSecrets" . | indent 6 }}
      containers:
        - image: {{ template  "kafka.metrics.kafka.image" . }}
          name: kafka-exporter
          args:
            - --kafka.server={{ template "kafka.fullname" . }}:{{ .Values.service.port }}
            - --web.listen-address=:{{ .Values.metrics.kafka.port }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.kafka.port }}
          {{- if .Values.metrics.kafka.resources }}
          resources: {{ toYaml .Values.metrics.kafka.resources | nindent 12 }}
          {{- end }}
{{- end }}
